[package]
name = "co_induction"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
z3 = "*"

[workspace]
members = ["ui", "engine", "verification"]